version: "3"
services:
   api:
      image: flask-api
      expose:
         - "3000"
   nginx: 
      build:
         context: .
         dockerfile: Dockerfile-nginx
      depends_on:
         - api
      ports:
         - "8080:80"
